server:
  port: 8081
spring:
  application:
    name: admin
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.36.33:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.36.33:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
mybatis-plus:
  type-aliases-package: com.xust.entity
logging:
  level:
    com.xust.mapper: debug

feign:
  client:
    config:
      default:
        read-timeout: 60000
        connect-timeout: 60000
